### ISSUE TITLE
未打开任何文件时直接点播放会导致程序崩溃

### ISSUE THREAD

**Issue by yisusheng** [xingchuanzhen/WPF-Music_Player#2]
**Describe the bug**
啊这╭(°A°`)╮ 如题，刚下载下来，一点播放，就崩溃了。

正在看大佬的代码学习

**Comment by Xing-Fax** [comment]
测试了，的确是一个BUG，我将会在下一个版本清除它，在添加过歌曲目录后不会出现该问题
