### ISSUE TITLE
字体不支持日语

### ISSUE THREAD

**Issue by korin5** [xingchuanzhen/WPF-Music_Player#5]
![QQ截图20221026192752](https://user-images.githubusercontent.com/63297666/198014851-ce575ac9-cbd5-498f-aadc-9d418ab0252a.jpg)

**Comment by Xing-Fax** [comment]
程序采用内嵌入字体，名称为"站酷快乐体2016修订版"，很遗憾此字体的开发者并没有提供对日语的支持，所以程序会使用系统默认字体作为显示字体
